version: '3.8'
services:
  chat:
    build:
      context: ./
    ports:
      - "8080:8080"
      - "10400:10400"
    depends_on:
      - chat_postgres
    env_file:
      - .env

  chat_postgres:
    image: postgres
    container_name: chat_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data

networks:
  server-network:
    driver: bridge

volumes:
  chat_postgres_data: