server:
  port: 8080
  servlet:
    context_path: /api

spring:
  datasource:
    url: jdbc:postgresql://${postgresql.url}/${postgresql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${postgresql.username}
    password: ${postgresql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
    flyway:
      url: jdbc:postgresql://${postgresql.url}/${postgresql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
      user: ${postgresql.username}
      password: ${postgresql.password}
      schema: public
      default-schema: public
      baseline-on-migrate: true
      check-location: true
      enabled: true

chatgpt:
  token: ${chatgpt.token}

logging.level.org.springframework.web: DEBUG