postgresql:
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  schema: ${POSTGRES_DB}
  url: ${POSTGRES_URL:localhost}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
